name: Build and Test

# Events like push, pull_request and etc that trigger the workflow
on:
  push:
    branches: [master, 'feature/**', 'bug/**']
  pull_request:
    branches: [master]

# Consider using a matrix strategy if building a library of a package with multiple versions
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # If you want to run on multiple OS, you can use a matrix strategy
    # strategy:
    #   matrix:
    #     # os: [ubuntu-latest, windows-latest, macos-latest]
    #     node-version: [20.x] # Specify the Node.js version you want to use

    steps:
      - uses: actions/checkout@v4 # using v4 for the latest features

      - name: Use Node.js
        uses: actions/setup-node@v4 # download and cache Node.js
        with:
          # node-version: '20.x'
          node-version: 20.x
          # Cache node modules to speed up the workflow
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
