name: Build and Test

on:
  push:
    branches: [master, 'feature/**', 'bug/**']
  pull_request:
    branches: [master]

# Consider using a matrix strategy if building a library of a package with multiple versions
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # using v4 for the latest features

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
